#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail  

readonly TARGET_HOST=pi@192.168.1.65
readonly TARGET_ARCH=aarch64-unknown-linux-gnu
readonly TARGET_PATH=/home/pi/grafana-pie
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/grafana-pie

if hash cross 2>/dev/null; then
        :
    else
        echo "cross not found. installing now..."
        cargo install cross
        wait
fi

cross build --release --target=${TARGET_ARCH}
rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_HOST} ${TARGET_PATH}